### ISSUE TITLE
open-simplex-noise is not the fastest noise library

### ISSUE THREAD

**Issue by xaroth8088** [joshforisha/open-simplex-noise-js#3]
I don't know if speed is even a design goal for you, so feel free to close this issue if it's not.  😄 

Basically, I decided to evaluate a handful of different noise generators while profiling texture-generation in one of my own projects and thought you might be interested to see how this library stacks up if nothing else.

jsperf is here: https://jsperf.com/fast-simplex-noise/1

**Comment by joshforisha** [comment]
There are no doubt improvements could be made, but essentially no, performance alone is not the goal of this library.

See the wiki entry [OpenSimplex noise](https://en.wikipedia.org/wiki/OpenSimplex_noise) and the related links for why it exists, and what trade-offs it has been designed for.
