### ISSUE TITLE
Better doc

### ISSUE THREAD

**Issue by linonetwo** [joshforisha/open-simplex-noise-js#8]
What is the range of output?

**Comment by linonetwo** [comment]
How to get a result like


<img width="645" alt="截屏2020-12-31 下午5 44 55" src="https://user-images.githubusercontent.com/3746270/103404809-e63b8900-4b8f-11eb-9170-241851d67540.png">

**Comment by joshforisha** [comment]
As mentioned in #7, this type of result is more accurately _fractal noise_, which this library can be the basis for. See my [joshforisha/fractal-noise-js](https://github.com/joshforisha/fractal-noise-js) for functions intended for that.
